### PR TITLE
Email bodyHtml template.

### PR DESCRIPTION
**Pull request by makasim**
currently there is no way to set content type for email.

### CODE REVIEW

**Comment by jeremymarc** [comment]
why did you use GEDMO instead of LifecycleCallbacks ?

**Comment by arnaud-lb** [comment]
It would be awesome to be able to set two bodies on each template: one for plain text, and an other for html (e.g. with simply two translatable fields `body` and `bodyHtml`). Both could be optional.

**Comment by jeremymarc** [comment]
+1

**Comment by jeremymarc** [comment]
looks like @GEDMO\Versioned is deprecated, and replaced EntityAudit : 
https://github.com/beberlei/DoctrineExtensions

**Comment by makasim** [comment]
@jeremymarc , @arnaud-lb updated, I removed `contentType` field and added `bodyHtml` instead, The admin page allows to set text and html body now.

**Comment by makasim** [comment]
close in favor #11

**Comment by makasim** [comment]
closed by mistake, it is still needed

**Comment by makasim** [comment]
> why did you use GEDMO instead of LifecycleCallbacks ?

as the bundle use currently uses some extensions like `Loggable`, `Versioned`, `Timestampable` already. Dont see a need of callbacks. Also it uses translatable here 

Before callback were used together with GEDMO for time fields, the job was done twice, I've just remove callbacks in favor of GEDMO

**Comment by makasim** [comment]
@jeremymarc could we merge it

/cc @arnaud-lb

**Comment by makasim** [comment]
@jeremymarc ping

**Pull request merged**
